discord widget
syscraft-mc/syscraft.dev pull request #18
Opened 2023-08-20 21:21 UTC by powercasgamer

2023-08-20 23:54 UTC, Turbotailz requested changes
Thanks! Just a couple things.

2023-08-20 23:54 UTC, Turbotailz commented on src/pages/index.astro
> +    <br style="margin-top: 0.5px"/>
Inline styles should be avoided at all costs. Could you please put this in the style sheet below?

2023-08-20 23:54 UTC, Turbotailz commented on .gitignore
> +pnpm-lock.yaml
It's not really a good idea to ignore lock files, but this project uses NPM, not PNPM so it doesn't really matter too much.

When installing you should be doing so with `npm install`

2023-08-20 23:55 UTC, Turbotailz commented
Also, because Cloudflare pages doesn't support PR previews from external repositories, could you please add a screenshot showing what it looks like?

2023-08-21 21:58 UTC, powercasgamer commented
> Also, because Cloudflare pages doesn't support PR previews from external repositories, could you please add a screenshot showing what it looks like?

![firefox_9A0VzyQMf6](https://github.com/syscraft-mc/syscraft.dev/assets/40437205/b27859bb-5901-4096-993f-88b4d99caf36)

2023-09-28 05:12 UTC, merged